### ISSUE TITLE
Тестове фейлват в master

### ISSUE THREAD

**Issue by vladimiroff** [Hackfmi/Diaphanum#13]
@RadoRado тръгна да деплойва проекта през Travis. Любопитното е, че тези тестовете фейлват само под PostgreSQL. 

``` python
....ssssssssssssssssssssssssssssssssssss............sssssss.ssssssssssssssssssssss.ssssssssssssssssssssssssssssssss...s.ssssssssssssssssssssssss..s.............ssssssssssssssssssssss..................................................................................................x.................................................................................................................................................................................................................................................................ss...............FFFFFF......F................

======================================================================

FAIL: test_edit_project_from_its_creator (projects.tests.ProjectTest)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/projects/tests.py", line 111, in test_edit_project_from_its_creator

self.assertEqual(response.status_code, 200)

AssertionError: 404 != 200

======================================================================

FAIL: test_edit_project_impossibru_from_this_user (projects.tests.ProjectTest)

this user is not the creator of the project

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/projects/tests.py", line 133, in test_edit_project_impossibru_from_this_user

self.assertEqual(response.status_code, 302)

AssertionError: 404 != 302

======================================================================

FAIL: test_edit_project_with_not_logged_in_user (projects.tests.ProjectTest)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/projects/tests.py", line 174, in test_edit_project_with_not_logged_in_user

self.assertEqual(response.status_code, 302)

AssertionError: 404 != 302

======================================================================

FAIL: test_edit_status_of_project_user_has_permissions (projects.tests.ProjectTest)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/projects/tests.py", line 91, in test_edit_status_of_project_user_has_permissions

self.assertEqual(response.status_code, 302)

AssertionError: 404 != 302

======================================================================

FAIL: test_master_can_edit_status (projects.tests.ProjectTest)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/projects/tests.py", line 194, in test_master_can_edit_status

self.assertEqual(response.status_code, 302)

AssertionError: 404 != 302

======================================================================

FAIL: test_master_cannot_edit_project (projects.tests.ProjectTest)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/projects/tests.py", line 214, in test_master_cannot_edit_project

self.assertEqual(response.status_code, 302)

AssertionError: 404 != 302

======================================================================

FAIL: test_display_protocol_by_id (protocols.tests.ProtocolTest)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/Hackfmi/Diaphanum/protocols/tests.py", line 386, in test_display_protocol_by_id

self.assertEqual(200, response.status_code)

AssertionError: 200 != 404

----------------------------------------------------------------------

Ran 584 tests in 34.445s

FAILED (failures=7, skipped=147, expected failures=1)

Destroying test database for alias 'default'...
```

**Comment by RadoRado** [comment]
И да се спомене - Issue 13 на Петък 13ти :calendar:

**Comment by Ivaylo-Bachvarov** [comment]
Което се пада международен ден на програмиста :dancers:

**Comment by hhursev** [comment]
[Check it out now](http://www.youtube.com/watch?v=SBClImpnfAg) :smiling_imp:

**Comment by RadoRado** [comment]
Евалата, всичко работи вече :)
